// Downloads the curated Google Fonts and generates two small committed files:
//   1. lib/batch-pdf/custom/fonts/metrics.generated.ts (deterministic width tables)
//   2. lib/batch-pdf/custom/fonts/font-urls.generated.ts (gstatic TTF URLs)
//
// The TTF binaries themselves are NOT committed — the server fetches them from
// the recorded CDN URLs at export time and caches them in memory.
//
// Run with: node scripts/generate-fonts.mjs
// Network access to fonts.googleapis.com / fonts.gstatic.com is required.

import { writeFile, readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import fontkit from "@pdf-lib/fontkit";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const fontsDir = path.join(root, "lib/batch-pdf/custom/fonts");

// A plain User-Agent makes the CSS2 API serve TTF (truetype) instead of woff2.
const PLAIN_UA = "Mozilla/5.0 (compatible; bulkCertGen-font-fetch/1.0)";

// ASCII printable range we build width tables for (32..126).
const ASCII = [];
for (let code = 32; code <= 126; code += 1) ASCII.push(String.fromCharCode(code));

function fileBaseName(id) {
  return id.replace(/\s+/g, "_");
}

const cssWeight = { normal: 400, bold: 700 };

async function fetchTtfUrl(family, weight) {
  const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family)}:wght@${cssWeight[weight]}&display=swap`;
  const res = await fetch(url, { headers: { "User-Agent": PLAIN_UA } });
  if (!res.ok) throw new Error(`CSS fetch failed for ${family} ${weight}: ${res.status}`);
  const css = await res.text();
  const match = css.match(/url\((https:\/\/[^)]+\.ttf)\)/);
  if (!match) throw new Error(`No TTF url for ${family} ${weight}`);
  return match[1];
}

function buildWidthTable(font) {
  const widths = {};
  let letterTotal = 0;
  let letterCount = 0;
  for (const char of ASCII) {
    // Read advance width straight from hmtx (glyphForCodePoint) rather than
    // font.layout(), which runs a positioning engine that throws on some fonts.
    let adv;
    try {
      adv = font.glyphForCodePoint(char.codePointAt(0)).advanceWidth;
    } catch {
      adv = font.unitsPerEm * 0.5;
    }
    const units = Math.round((adv / font.unitsPerEm) * 1000);
    widths[char] = units;
    if (/[A-Za-z]/.test(char)) {
      letterTotal += units;
      letterCount += 1;
    }
  }
  const fallback = letterCount ? Math.round(letterTotal / letterCount) : 500;
  return { widths, fallback };
}

async function main() {
  const { fonts } = JSON.parse(
    await readFile(path.join(fontsDir, "font-list.json"), "utf8"),
  );

  const metrics = {};
  const urls = {};
  const googleFonts = fonts.filter((f) => f.source === "google");

  for (const font of googleFonts) {
    metrics[font.id] = {};
    for (const weight of font.weights) {
      process.stdout.write(`  ${font.id} (${weight})… `);
      const ttfUrl = await fetchTtfUrl(font.id, weight);
      const bytes = new Uint8Array(await (await fetch(ttfUrl)).arrayBuffer());
      const parsed = fontkit.create(bytes);
      metrics[font.id][weight] = buildWidthTable(parsed);
      urls[`${fileBaseName(font.id)}-${weight}`] = ttfUrl;
      console.log(`${(bytes.length / 1024).toFixed(0)}kb`);
    }
  }

  const header = `// AUTO-GENERATED by scripts/generate-fonts.mjs — do not edit by hand.
// Per-font glyph advance widths in 1000-unit em space (ASCII 32..126),
// extracted from the embedded TTF so preview measurement matches the PDF.

export type FontWidthTable = {
  widths: Record<string, number>;
  fallback: number;
};

export const FONT_METRICS: Record<
  string,
  Partial<Record<"normal" | "bold", FontWidthTable>>
> = ${JSON.stringify(metrics, null, 2)};
`;

  await writeFile(path.join(fontsDir, "metrics.generated.ts"), header);

  const urlsModule = `// AUTO-GENERATED by scripts/generate-fonts.mjs — do not edit by hand.
// Resolved fonts.gstatic.com TTF URLs keyed by "<fileBaseName>-<weight>".
// The server fetches and caches these at export time (no committed binaries).

export const FONT_FILE_URLS: Record<string, string> = ${JSON.stringify(urls, null, 2)};
`;
  await writeFile(path.join(fontsDir, "font-urls.generated.ts"), urlsModule);

  console.log(`\nWrote metrics + URLs for ${googleFonts.length} fonts.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
