// Downloads the curated Google Fonts and generates two small committed files:
//   1. lib/batch-pdf/custom/fonts/metrics.generated.ts (deterministic width tables)
//   2. lib/batch-pdf/custom/fonts/font-urls.generated.ts (gstatic font URLs)
//
// The TTF binaries themselves are NOT committed — the server fetches them from
// the recorded CDN URLs at export time and caches them in memory.
//
// Run with: node scripts/generate-fonts.mjs
// Network access to fonts.googleapis.com / fonts.gstatic.com is required.

import { writeFile, readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";
import fontkit from "@pdf-lib/fontkit";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const fontsDir = path.join(root, "lib/batch-pdf/custom/fonts");

// A plain User-Agent often makes the CSS2 API serve TTF (truetype), but
// text-subset responses may still use WOFF/WOFF2. fontkit can inspect the
// served bytes either way, and the server embeds the same bytes.
const PLAIN_UA = "Mozilla/5.0 (compatible; bulkCertGen-font-fetch/1.0)";

// Printable ASCII plus representative characters that commonly appear in
// names, addresses, and the broad Noto script fonts. Coverage is still exact:
// a character is emitted only when the downloaded TTF maps it to a real glyph.
const ASCII = [];
for (let code = 32; code <= 126; code += 1) ASCII.push(String.fromCharCode(code));

const LATIN_NAME_CHARS =
  "ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿ" +
  "ĀāĂăĄąĆćČčĎďĐđĒēĘęĚěĞğİıŁłŃńŇňŐőŒœŔŕŘřŚśŞşȘșŤťȚțŪūŮůŰűŸŹźŻżŽž";

const COMMON_SCRIPT_CHARS =
  "ΑλέξανδροςМарияИванПетров" +
  "محمدعليليلى" +
  "דניאלשרה" +
  "आरवअनन्या" +
  "田中太郎山田花子" +
  "张伟王芳" +
  "張偉王芳" +
  "김민준이지은" +
  "สมชายมาลี";

const MEASURED_CHARS = Array.from(new Set([...ASCII.join(""), ...LATIN_NAME_CHARS, ...COMMON_SCRIPT_CHARS]));

function fileBaseName(id) {
  return id.replace(/\s+/g, "_");
}

const cssWeight = { normal: 400, bold: 700 };

async function fetchFontUrl(family, weight) {
  const text = MEASURED_CHARS.join("");
  const url =
    `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family)}:wght@${cssWeight[weight]}` +
    `&text=${encodeURIComponent(text)}&display=swap`;
  const res = await fetch(url, { headers: { "User-Agent": PLAIN_UA } });
  if (!res.ok) throw new Error(`CSS fetch failed for ${family} ${weight}: ${res.status}`);
  const css = await res.text();
  const match = css.match(/url\((https:\/\/[^)]+)\)/);
  if (!match) throw new Error(`No font url for ${family} ${weight}: ${css.slice(0, 300)}`);
  return match[1];
}

function buildWidthTable(font) {
  const widths = {};
  let letterTotal = 0;
  let letterCount = 0;
  for (const char of MEASURED_CHARS) {
    // Read advance width straight from hmtx (glyphForCodePoint) rather than
    // font.layout(), which runs a positioning engine that throws on some fonts.
    let adv;
    try {
      const glyph = font.glyphForCodePoint(char.codePointAt(0));
      if (!glyph || glyph.id === 0) continue;
      adv = glyph.advanceWidth;
    } catch {
      continue;
    }
    const units = Math.round((adv / font.unitsPerEm) * 1000);
    widths[char] = units;
    if (/[A-Za-z]/.test(char)) {
      letterTotal += units;
      letterCount += 1;
    }
  }
  const fallback = letterCount ? Math.round(letterTotal / letterCount) : 500;
  return { widths, fallback };
}

async function main() {
  const { fonts } = JSON.parse(
    await readFile(path.join(fontsDir, "font-list.json"), "utf8"),
  );

  const metrics = {};
  const urls = {};
  const googleFonts = fonts.filter((f) => f.source === "google");

  for (const font of googleFonts) {
    metrics[font.id] = {};
    for (const weight of font.weights) {
      process.stdout.write(`  ${font.id} (${weight})… `);
      const fontUrl = await fetchFontUrl(font.id, weight);
      const bytes = new Uint8Array(await (await fetch(fontUrl)).arrayBuffer());
      const parsed = fontkit.create(bytes);
      metrics[font.id][weight] = buildWidthTable(parsed);
      urls[`${fileBaseName(font.id)}-${weight}`] = fontUrl;
      console.log(`${(bytes.length / 1024).toFixed(0)}kb`);
    }
  }

const header = `// AUTO-GENERATED by scripts/generate-fonts.mjs — do not edit by hand.
// Per-font glyph advance widths in 1000-unit em space, extracted from the
// embedded TTF so preview measurement and glyph coverage match the PDF.

export type FontWidthTable = {
  widths: Record<string, number>;
  fallback: number;
};

export const FONT_METRICS: Record<
  string,
  Partial<Record<"normal" | "bold", FontWidthTable>>
> = ${JSON.stringify(metrics, null, 2)};
`;

  await writeFile(path.join(fontsDir, "metrics.generated.ts"), header);

  const urlsModule = `// AUTO-GENERATED by scripts/generate-fonts.mjs — do not edit by hand.
// Resolved fonts.gstatic.com font URLs keyed by "<fileBaseName>-<weight>".
// The server fetches and caches these exact bytes at export time.

export const FONT_FILE_URLS: Record<string, string> = ${JSON.stringify(urls, null, 2)};
`;
  await writeFile(path.join(fontsDir, "font-urls.generated.ts"), urlsModule);

  console.log(`\nWrote metrics + URLs for ${googleFonts.length} fonts.`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
