import type { BatchPdfTemplate } from "./types.ts";

export const CLASSIC_CERTIFICATE_TEMPLATE: BatchPdfTemplate = {
  id: "classic-certificate",
  name: "Classic Certificate",
  shortName: "Certificate",
  description:
    "Generate simple certificates for courses, workshops, awards, and participation.",
  category: "certificate",
  version: 1,
  free: true,
  recommendedFor: [
    "course completion",
    "workshops",
    "awards",
    "participation certificates",
  ],
  fields: [
    {
      key: "name",
      label: "Recipient name",
      type: "text",
      required: true,
      aliases: ["name", "full name", "student name", "recipient"],
      maxLength: 80,
      placeholder: "Jane Smith",
    },
    {
      key: "course",
      label: "Course or award",
      type: "text",
      required: true,
      aliases: ["course", "program", "award", "title"],
      maxLength: 120,
      placeholder: "Intro to Data Skills",
    },
    {
      key: "date",
      label: "Date",
      type: "date",
      required: true,
      aliases: ["date", "completion date", "award date"],
      maxLength: 40,
      placeholder: "June 15, 2026",
    },
    {
      key: "issuer",
      label: "Issuer",
      type: "text",
      required: false,
      aliases: ["issuer", "organization", "company", "school"],
      maxLength: 100,
      placeholder: "Very Simple Academy",
    },
  ],
};

export const NAME_BADGE_TEMPLATE: BatchPdfTemplate = {
  id: "name-badge",
  name: "Name Badge",
  shortName: "Badge",
  description:
    "Create clean event badges with names, roles, companies, and optional table details.",
  category: "badge",
  version: 1,
  free: true,
  recommendedFor: ["meetups", "conferences", "workshops", "visitor badges"],
  fields: [
    {
      key: "name",
      label: "Name",
      type: "text",
      required: true,
      aliases: ["name", "full name", "attendee", "guest"],
      maxLength: 80,
      placeholder: "Jane Smith",
    },
    {
      key: "role",
      label: "Role or title",
      type: "text",
      required: false,
      aliases: ["role", "title", "job title", "position"],
      maxLength: 70,
      placeholder: "Program Lead",
    },
    {
      key: "company",
      label: "Company",
      type: "text",
      required: false,
      aliases: ["company", "organization", "team", "school"],
      maxLength: 80,
      placeholder: "North Labs",
    },
    {
      key: "group",
      label: "Group",
      type: "text",
      required: false,
      aliases: ["group", "track", "table", "cohort"],
      maxLength: 40,
      placeholder: "Table 4",
    },
  ],
};

export const MAILING_LABEL_TEMPLATE: BatchPdfTemplate = {
  id: "mailing-label",
  name: "Mailing Label",
  shortName: "Label",
  description:
    "Format names and postal addresses into printable mailing labels.",
  category: "label",
  version: 1,
  free: true,
  recommendedFor: ["mailing lists", "shipping labels", "event packets"],
  fields: [
    {
      key: "name",
      label: "Recipient name",
      type: "text",
      required: true,
      aliases: ["name", "full name", "recipient", "contact"],
      maxLength: 80,
      placeholder: "Jane Smith",
    },
    {
      key: "address_line_1",
      label: "Address line 1",
      type: "address",
      required: true,
      aliases: ["address", "address 1", "address line 1", "street"],
      maxLength: 120,
      placeholder: "123 Main St",
    },
    {
      key: "address_line_2",
      label: "Address line 2",
      type: "address",
      required: false,
      aliases: ["address 2", "address line 2", "unit", "apartment"],
      maxLength: 120,
      placeholder: "Apt 4",
    },
    {
      key: "city",
      label: "City",
      type: "text",
      required: true,
      aliases: ["city", "town", "municipality"],
      maxLength: 80,
      placeholder: "Toronto",
    },
    {
      key: "region",
      label: "Province or state",
      type: "text",
      required: true,
      aliases: ["province", "state", "region", "province/state"],
      maxLength: 40,
      placeholder: "ON",
    },
    {
      key: "postal_code",
      label: "Postal or ZIP code",
      type: "text",
      required: true,
      aliases: ["postal code", "zip", "zip code", "postcode"],
      maxLength: 20,
      placeholder: "M5V 1A1",
    },
  ],
};

export const APPOINTMENT_CARD_TEMPLATE: BatchPdfTemplate = {
  id: "appointment-card",
  name: "Appointment Card",
  shortName: "Appointment",
  description:
    "Make small reminder cards with the appointment date, time, place, and notes.",
  category: "card",
  version: 1,
  free: true,
  recommendedFor: ["clinics", "service calls", "consultations", "office visits"],
  fields: [
    {
      key: "name",
      label: "Name",
      type: "text",
      required: true,
      aliases: ["name", "full name", "client", "patient"],
      maxLength: 80,
      placeholder: "Jane Smith",
    },
    {
      key: "date",
      label: "Date",
      type: "date",
      required: true,
      aliases: ["date", "appointment date", "visit date"],
      maxLength: 40,
      placeholder: "June 15, 2026",
    },
    {
      key: "time",
      label: "Time",
      type: "text",
      required: true,
      aliases: ["time", "appointment time", "visit time"],
      maxLength: 30,
      placeholder: "10:30 AM",
    },
    {
      key: "location",
      label: "Location",
      type: "text",
      required: true,
      aliases: ["location", "address", "office", "room"],
      maxLength: 120,
      placeholder: "Main Office",
    },
    {
      key: "notes",
      label: "Notes",
      type: "multiline",
      required: false,
      aliases: ["notes", "instructions", "details", "reminder"],
      maxLength: 180,
      placeholder: "Bring ID",
    },
  ],
};

export const BATCH_PDF_TEMPLATES: BatchPdfTemplate[] = [
  CLASSIC_CERTIFICATE_TEMPLATE,
  NAME_BADGE_TEMPLATE,
  MAILING_LABEL_TEMPLATE,
  APPOINTMENT_CARD_TEMPLATE,
];
